// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeeuC9VNStl5rtlz4m9uxKqfXxT8T-N5w',
    appId: '1:739717417688:web:c48e274a29901053df65ad',
    messagingSenderId: '739717417688',
    projectId: 'flutter-chat-3c9f1',
    authDomain: 'flutter-chat-3c9f1.firebaseapp.com',
    storageBucket: 'flutter-chat-3c9f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABPtvqr-tO3uharzoVhmN2gHWr5yAH_4s',
    appId: '1:739717417688:android:e479a00b81c823bbdf65ad',
    messagingSenderId: '739717417688',
    projectId: 'flutter-chat-3c9f1',
    storageBucket: 'flutter-chat-3c9f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKM0p6NQ-LKm25dba_5Yw0JfczBg9ehAg',
    appId: '1:739717417688:ios:20913a68215989a9df65ad',
    messagingSenderId: '739717417688',
    projectId: 'flutter-chat-3c9f1',
    storageBucket: 'flutter-chat-3c9f1.appspot.com',
    iosClientId: '739717417688-nnnp8r8i9lv9531lsr8mjob5hql2lob0.apps.googleusercontent.com',
    iosBundleId: 'com.naman.chat.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKM0p6NQ-LKm25dba_5Yw0JfczBg9ehAg',
    appId: '1:739717417688:ios:d2f6e59f3217f329df65ad',
    messagingSenderId: '739717417688',
    projectId: 'flutter-chat-3c9f1',
    storageBucket: 'flutter-chat-3c9f1.appspot.com',
    iosClientId: '739717417688-12bt44ck5fgovu3tuo9jj4mho1okjs7s.apps.googleusercontent.com',
    iosBundleId: 'com.naman.chat.chat.RunnerTests',
  );
}
